/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.hslu.prg2.calculator;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import javax.swing.JButton;

/**
 *
 * @author mogria
 */
public class Calculator extends javax.swing.JFrame implements ActionListener {

    int operand1;
    int operand2;
    int operator;
    int result;
    boolean firstOperand;
    boolean displayResult;
    
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        
        operand1 = operand2 = operator = result = 0;
        firstOperand = true;
        displayResult = false;
        
        JButton []buttons = {
            buttonNumber0,
            buttonNumber1,
            buttonNumber2,
            buttonNumber3,
            buttonNumber4,
            buttonNumber5,
            buttonNumber6,
            buttonNumber7,
            buttonNumber8,
            buttonNumber9,
            buttonAdd,
            buttonSubtract,
            buttonMultiply,
            buttonDivide,
            buttonResult,
            buttonClear,
            buttonStoreMemory,
            buttonRetrieveMemory,
            buttonClearMemory
        };
        
        for (JButton button : buttons) {
            button.addActionListener(this);
        }
    }
    
    public void clear() {
        
        firstOperand = true;
        result = 0;
        operand1 = operand2 = 0;
    }
    
    public void toggleOperand() {
        firstOperand = !firstOperand;
    }
    
    public int getOperandValue() {
        return firstOperand ? operand1 : operand2;
    }
    
    public void setOperandValue(int value) {
        if(firstOperand) {
            operand1 = value;
        } else {
            operand2 = value;
        }
    }
    
    
    @Override
    public void actionPerformed(ActionEvent e) {
        char buttonLabel = (e.getActionCommand()).charAt(0);
        switch(buttonLabel) {
            case '=':
                
                result = 0;
                displayResult = true;
                break;
            case '+':
                operator = 1;
                toggleOperand();
                break;
            case '-':
                operator = 2;
                toggleOperand();
                break;
            case '*':
                operator = 3;
                toggleOperand();
                break;
            case '/':
                operator = 4;
                toggleOperand();
                break;
            case 'C':
                clear();
                displayResult = false;
            default:
                int lastDigit = buttonLabel -  48 /* '0' */;
                int value = getOperandValue();
                value *= 10;
                value += lastDigit;
                setOperandValue(value);
                displayResult = false;
                break;
        }
        
        if(displayResult) {
            outLabel.setText("" + result);
        } else {
            outLabel.setText("" + getOperandValue());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        outLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        buttonNumber7 = new javax.swing.JButton();
        buttonNumber8 = new javax.swing.JButton();
        buttonNumber9 = new javax.swing.JButton();
        buttonDivide = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        buttonNumber4 = new javax.swing.JButton();
        buttonNumber5 = new javax.swing.JButton();
        buttonNumber6 = new javax.swing.JButton();
        buttonMultiply = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        buttonNumber1 = new javax.swing.JButton();
        buttonNumber2 = new javax.swing.JButton();
        buttonNumber3 = new javax.swing.JButton();
        buttonSubtract = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        buttonNumber0 = new javax.swing.JButton();
        buttonS = new javax.swing.JButton();
        buttonResult = new javax.swing.JButton();
        buttonAdd = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        buttonClear = new javax.swing.JButton();
        buttonStoreMemory = new javax.swing.JButton();
        buttonRetrieveMemory = new javax.swing.JButton();
        buttonClearMemory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(250, 210));
        setMinimumSize(new java.awt.Dimension(250, 210));
        setPreferredSize(new java.awt.Dimension(250, 210));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        textField.setEditable(false);
        textField.setBackground(new java.awt.Color(255, 255, 255));
        textField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textField.setToolTipText("");
        jPanel1.add(textField);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 1));

        outLabel.setText(" ");
        jPanel2.add(outLabel);

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        buttonNumber7.setText("7");
        buttonNumber7.setToolTipText("");
        buttonNumber7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber7ActionPerformed(evt);
            }
        });
        jPanel3.add(buttonNumber7);

        buttonNumber8.setText("8");
        jPanel3.add(buttonNumber8);

        buttonNumber9.setText("9");
        jPanel3.add(buttonNumber9);

        buttonDivide.setText("/");
        jPanel3.add(buttonDivide);

        getContentPane().add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        buttonNumber4.setText("4");
        jPanel4.add(buttonNumber4);

        buttonNumber5.setText("5");
        jPanel4.add(buttonNumber5);

        buttonNumber6.setText("6");
        jPanel4.add(buttonNumber6);

        buttonMultiply.setText("*");
        jPanel4.add(buttonMultiply);

        getContentPane().add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        buttonNumber1.setText("1");
        jPanel5.add(buttonNumber1);

        buttonNumber2.setText("2");
        jPanel5.add(buttonNumber2);

        buttonNumber3.setText("3");
        buttonNumber3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber3ActionPerformed(evt);
            }
        });
        jPanel5.add(buttonNumber3);

        buttonSubtract.setText("-");
        jPanel5.add(buttonSubtract);

        getContentPane().add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        buttonNumber0.setText("0");
        jPanel6.add(buttonNumber0);

        buttonS.setText("S");
        jPanel6.add(buttonS);

        buttonResult.setText("=");
        jPanel6.add(buttonResult);

        buttonAdd.setText("+");
        jPanel6.add(buttonAdd);

        getContentPane().add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        buttonClear.setText("C");
        jPanel7.add(buttonClear);

        buttonStoreMemory.setText("sM");
        jPanel7.add(buttonStoreMemory);

        buttonRetrieveMemory.setText("rM");
        jPanel7.add(buttonRetrieveMemory);

        buttonClearMemory.setText("cM");
        jPanel7.add(buttonClearMemory);

        getContentPane().add(jPanel7);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNumber7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonNumber7ActionPerformed

    private void buttonNumber3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonNumber3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonClearMemory;
    private javax.swing.JButton buttonDivide;
    private javax.swing.JButton buttonMultiply;
    private javax.swing.JButton buttonNumber0;
    private javax.swing.JButton buttonNumber1;
    private javax.swing.JButton buttonNumber2;
    private javax.swing.JButton buttonNumber3;
    private javax.swing.JButton buttonNumber4;
    private javax.swing.JButton buttonNumber5;
    private javax.swing.JButton buttonNumber6;
    private javax.swing.JButton buttonNumber7;
    private javax.swing.JButton buttonNumber8;
    private javax.swing.JButton buttonNumber9;
    private javax.swing.JButton buttonResult;
    private javax.swing.JButton buttonRetrieveMemory;
    private javax.swing.JButton buttonS;
    private javax.swing.JButton buttonStoreMemory;
    private javax.swing.JButton buttonSubtract;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel outLabel;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables

}
